config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#question1'
  get 'question1/answer', to: 'home#question1'
  get 'question2/answer', to: 'home#question2'
  get 'question3/answer', to: 'home#question3'
  get 'question4/answer', to: 'home#question4'
  get 'question5/answer', to: 'home#question5'

  post 'api/event_logs', to: 'event_log#create_event'
  resources :event_log, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_log.rb
# frozen_string_literal: true

class EventLog < ApplicationRecord
  validates :event_name, presence: true
  validates :timestamp, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_log_controller.rb
# frozen_string_literal: true

class EventLogController < ApplicationController
  protect_from_forgery with: :null_session, only: :create_event

  def index
    @event_logs = EventLog.last(1_000)
  end

  def create_event
    if event_params[:event_name].nil? || event_params[:timestamp].nil?
      render json: { success: false, errors: 'Params is invalid' }
    else
      EventLogJobWorker.perform_async(event_params[:event_name], event_params[:timestamp])
      render json: { success: true }
    end
  end

  private

  def event_params
    @event_params ||= params.permit(:event_name, :timestamp).tap do |p|
      p[:event_name] = p[:event_name].strip if p[:event_name]
      p[:timestamp] = p[:timestamp].strip if p[:timestamp]
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def question1
    services = Questions::Question1.new(question1_params[:array_input])
    if services.execute
      @array_input = services.source
      @array_ascending = services.asc_array
      @arrray_descending = services.desc_array
    else
      @errors = 'Fail execute sort with your params'
    end
  end

  def question2
    services = Questions::Question2.new(question2_params[:array1], question2_params[:array2])
    if services.execute
      @array1 = services.array1
      @array2 = services.array2
      @result_array = services.result_array
    else
      @errors = 'Fail execute question2'
    end
  end

  def question3
    services = Questions::Question3.new(question_params[:source])
    result = services.execute
    @source = services.source
    if result.present?
      @character = result.first[0]
      @index = result.first[1]
    else
      @errors = 'Fail execute question3'
    end
  end

  def question4
    services = Questions::Question4.new(question_params[:source])
    if services.execute
      @source = services.source
      @output1 = services.output1
      @output2 = services.output2
    else
      @errors = 'Fail execute question4'
    end
  end

  def question5
    MasterLogger.info 'Received request for question5'
  end

  private

  def question1_params
    @question1_params ||= params.tap do |p|
      p[:array_input] = p[:array_input].split(',').map(&:to_i) if p[:array_input]
    end
  end

  def question2_params
    @question2_params ||= params.tap do |p|
      p[:array1] = p[:array1].split(',').map(&:to_i) if p[:array1]
      p[:array2] = p[:array2].split(',').map(&:to_i) if p[:array2]
    end
  end

  def question_params
    @question_params ||= params.tap do |p|
      p[:source] = p[:source].strip if p[:source]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/event_log/index.html.erb
<h1>BUI DUC AN - Skylab</h1>
<h2> question 5:  </h2>
<p> List of event logs </p>
<% @event_logs.each do |event| %>
	<%= "Id: #{event.id}, event_name: #{event.event_name}, timestamp: #{event.timestamp}" %>
</br>
<% end %>

app/views/home/question1.html.erb
<h1>BUI DUC AN - Skylab</h1>
<h2> question 1:  </h2>
<p>Implement bubble sort (highest to lowest and lowest to highest) in Ruby for array
</p>
<%= @array_input %>
<h4> Change you input  </h4>
<h1> <%= @errors if @errors %></h1>
<%= form_tag(question1_answer_path, :method => :get) do %>
  <%= label_tag(:array_input, "Enter your array seperate by \, :") %>
  <%= text_field_tag(:array_input) %>
  <%= submit_tag('Ok') %>
<% end %>

<h4> Array ascending : <%= @array_ascending %>
	</h4>
<h4> Array descending: <%= @arrray_descending %>
</h4>

app/views/home/question2.html.erb
<h1>BUI DUC AN - Skylab</h1>
<h2> question 2:  </h2>
<p>
	Given 2 integer arrays, find the common elements between 2 arrays
</p>
<p>
	Array 1: <%= @array1 %>
</p>
<p>
	Array 2: <%= @array2 %>
</p>

<h4> Change you input  </h4>
<h1> <%= @errors if @errors %></h1>
<%= form_tag(question2_answer_path, :method => :get) do %>
  <%= label_tag(:array1, "Enter array 1 seperate by \, :") %>
  <%= text_field_tag(:array1) %>
  <br>
  <%= label_tag(:array2, "Enter array 2 seperate by \, :") %>
  <%= text_field_tag(:array2) %>
  <br>
  <%= submit_tag('Ok') %>
<% end %>
<h4>
	Result: <%=	@result_array %>
</h4>

app/views/home/question3.html.erb
<h1>BUI DUC AN - Skylab</h1>
<h2> question 3:  </h2>
<p>
	 Find the first non-repeated character in a String:
	 <%= @source %>
</p>

<h4> Change you input  </h4>
<h1> <%= @errors if @errors %></h1>
<%= form_tag(question3_answer_path, :method => :get) do %>
  <%= label_tag(:source, "Enter your string:") %>
  <%= text_field_tag(:source) %>
  <br>
  <%= submit_tag('Ok') %>
<% end %>
<h4>
	First non-repeated character is : <%=	@character %>
	with index <%= @index %>
</h4>

app/views/home/question4.html.erb
<h1>BUI DUC AN - Skylab</h1>
<h2> question 4:  </h2>
<p>
	 Count the number of the character in a String after that Sort the character by the number from highest to lowest and lowest to highestEx:

</p>
	<p> Input: <%= @source %></p>
<h4> Change you input  </h4>
<h1>
	<%= @errors if @errors %>
</h1>
<%= form_tag(question4_answer_path, :method => :get) do %>
  <%= label_tag(:source, "Enter your string:") %>
  <%= text_field_tag(:source) %>
  <br>
  <%= submit_tag('Ok') %>
<% end %>
<h4>
	Output 1: <%= @output1 %>
</h4>

<h4>
	Output 2: <%= @output2 %>
</h4>

app/views/home/question5.html.erb
<h1>BUI DUC AN - Skylab</h1>
<h2> question 5:  </h2>
<p>
	Create logger class support multiple outputCreate logger class support multiple output such as a console, file ( in log/ folder ), mail.
</p>

<h2>I create class MultiLogger::Base for multiple outputCreate</h2>
<h2>I create class MultiLogger::FileOutputter for input to file</h2>
<h2> How to use: </h2>
<h3>
	std_out = Logger.new(STDOUT)
</br>
	MasterLogger = MultiLogger::Base.new(loggers: std_out, level: 'INFO')
</br>
	file_output = MultiLogger::FileOutputter.new('log_file.log') #log_file.log is file name in file log, default path is 'tmp/file_log'
	<br>
	MasterLogger.add_logger file_output #add new output type, can handle multiple type here
</h3>

<h2>Default logger init in this app is MasterLogger with support INFO level</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkylabTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <table>
      <tr>
        <td><%= link_to 'Question1', question1_answer_path %></td>
        <td><%= link_to 'Question2', question2_answer_path %></td>
        <td><%= link_to 'Question3', question3_answer_path %></td>
        <td><%= link_to 'Question4', question4_answer_path %></td>
        <td><%= link_to 'LogsEventAPIQuestion', event_log_index_path %></td>
        <td><%= link_to 'Question5', question5_answer_path %></td>
      </tr>
    </table>
    <%= yield %>
  </body>
</html>